package com.rejowan.chargify.presentation.theme

import androidx.compose.ui.graphics.Color

// Light theme colors - Purple based (matching dark theme #7265E2)
val primaryLight = Color(0xFF5B4FC7)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFE8E0FF)
val onPrimaryContainerLight = Color(0xFF1C0062)
val secondaryLight = Color(0xFF605C71)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE6DFF9)
val onSecondaryContainerLight = Color(0xFF1C192C)
val tertiaryLight = Color(0xFF2E7D32)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB8F5B8)
val onTertiaryContainerLight = Color(0xFF002106)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF8FF)
val onBackgroundLight = Color(0xFF1C1B20)
val surfaceLight = Color(0xFFFDF8FF)
val onSurfaceLight = Color(0xFF1C1B20)
val surfaceVariantLight = Color(0xFFE6E0EF)
val onSurfaceVariantLight = Color(0xFF48454F)
val outlineLight = Color(0xFF797680)
val outlineVariantLight = Color(0xFFCAC4D3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF313036)
val inverseOnSurfaceLight = Color(0xFFF4EFF7)
val inversePrimaryLight = Color(0xFFCDBDFF)
val surfaceDimLight = Color(0xFFDDD8E1)
val surfaceBrightLight = Color(0xFFFDF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F2FB)
val surfaceContainerLight = Color(0xFFF2ECF5)
val surfaceContainerHighLight = Color(0xFFECE6EF)
val surfaceContainerHighestLight = Color(0xFFE6E1EA)

// Dark theme colors - Purple based
val primaryDark = Color(0xFF7265E2)
val onPrimaryDark = Color(0xFFE4DFFF)
val primaryContainerDark = Color(0xFF5C6BC0)
val onPrimaryContainerDark = Color(0xFFBBDEFB)
val secondaryDark = Color(0xFFAD98FF)
val onSecondaryDark = Color(0xFFE4DFFF)
val secondaryContainerDark = Color(0xFF474459)
val onSecondaryContainerDark = Color(0xFFE4DFF9)
val tertiaryDark = Color(0xFF99D4A3)
val onTertiaryDark = Color(0xFF003918)
val tertiaryContainerDark = Color(0xFF17512B)
val onTertiaryContainerDark = Color(0xFFB4F1BD)
val errorDark = Color(0xFFDC393B)
val onErrorDark = Color(0xFFD5D5D5)
val errorContainerDark = Color(0xFFFF746B)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF131318)
val onBackgroundDark = Color(0xFFE5E1E9)
val surfaceDark = Color(0xFF131318)
val onSurfaceDark = Color(0xFFE5E1E9)
val surfaceVariantDark = Color(0xFF47464F)
val onSurfaceVariantDark = Color(0xFFC9C5D0)
val outlineDark = Color(0xFF928F99)
val outlineVariantDark = Color(0xFF47464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE5E1E9)
val inverseOnSurfaceDark = Color(0xFF313036)
val inversePrimaryDark = Color(0xFF5D5791)
val surfaceDimDark = Color(0xFF131318)
val surfaceBrightDark = Color(0xFF3A383E)
val surfaceContainerLowestDark = Color(0xFF0E0E13)
val surfaceContainerLowDark = Color(0xFF1C1B20)
val surfaceContainerDark = Color(0xFF201F25)
val surfaceContainerHighDark = Color(0xFF2A292F)
val surfaceContainerHighestDark = Color(0xFF35343A)
